### PR TITLE
Update gem

### PR DESCRIPTION
**Pull request by elizamarcum**
Once we've reviewed and merged everything related to this in p3p/wellnest, we should promote this branch to master (not by merging, but by force pushing).

The easiest way to review these changes is by looking at the two commits I added.

### CODE REVIEW

**Comment by panozzaj** [comment]
Has conflicts at this time.

**Comment by panozzaj** [comment]
Overall I think these changes look good. Also appreciate the documentation update!

**Comment by elizamarcum** [comment]
My intention is to force push it to master, so that the branch history is
rebaseable off of OneLogin/ruby-saml for future updates.

On Feb 12, 2017, at 8:49 AM, Anthony Panozzo <notifications@github.com>
wrote:

Has conflicts at this time.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OurHealth/ruby-saml/pull/1#issuecomment-279223392>, or mute
the thread

**Comment by panozzaj** [comment]
Got it, my bad.

**Review by shipstar — APPROVED** [review]
Looks good to me. Thanks for tackling this!

**Pull request merged**
